//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week5Day2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int SupplierID { get; set; }
        public int MovieID { get; set; }
        public int Copies { get; set; }
    
        public virtual Movy Movy { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
